#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Script display information for its subdomains


domain_info() {
	dig "$2.$1" | awk '/;; ANSWER SECTION/ {getline;
	printf "The subdomain %s is a %s record and points to %s\n", subd, $4, $5}' subd="$2"
}

if [ "$#" == 1 ]
then
  domain_info "$1" "www"
  domain_info "$1" "lb-01"
  domain_info "$1" "web-01"
  domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_info "$1" "$2"
fi
