#!/usr/bin/env bash
# script transfers file from our client to a server
# Accepts 4 parameters:
# The path of file to be transfered
# The IP of server to transfer a file to
# the Username scp connects with
# The path to the SSH private key that scp uses
if [ $# -lt 4 ]; then
       echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else
    scp -o 'StrictHostKeyChecking no' -i "$4" "$1" "$3"@"$2":~
fi
