#!/usr/bin/env bash
# Installs nginx on web-01 server
# & create html index page

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
