#!/usr/bin/env bash
# Configure nginx server
sudo apt-get update
sudo apt-get install nginx -y
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4? permanent; }' /etc/nginx/sites-available/default
sudo service nginx start
