#!/usr/bin/env bash
# Configures NGINX server
# Creates a new 404 page
sudo apt-get update
sudo apt-get install nginx -y
sudo touch /var/www/html/costume_404.html
sudo echo "Ceci n'est pas une page" | sudo tee "/var/www/html/costume_404.html"
sudo sed -i "24 i \\\terror_page 404 /costume_404.html;" /etc/nginx/sites-enabled/default
sudo service nginx restart
