#!/usr/bin/env bash
# Ascertains Ubuntus Nginx server & listen port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(ps -e 'nginx' | more -1)"
