#!/usr/bin/env bash
# Ascertains Ubuntus Nginx server & listen port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
