#!/usr/bin/env bash
# Ascertains Ubuntu container’s Nginx server & listen port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(ps -e | more -1)"
