#!/usr/bin/env bash
# Bash script displays the time for 12 hours and 59 minutes:
x=0
y=0
while [ $x -le 12 ]
do
	y=1
    echo "Hour: $x"
    while [ $y -le 59 ]
    do
        echo $y
        ((y++))
    done
    ((x++))
done
