#!/usr/bin/env bash
# UFW Configuration
# blocks all incoming traffic, except the following
sudo ufw default deny incoming
# Allow connections TCP; (SSH, HTTPS/SSL, HTTP)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
