#!/usr/bin/env bash
#Bash script configures Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
