#!/usr/bin/env bash
# Run Nginx as Nginx user
sudo pkill apache2
sudo chown www-data:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo service nginx reload
