#!/usr/bin/env bash
# Run Nginx as Nginx user
sudo sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
