#!/usr/bin/env bash
# Run Nginx as Nginx user
sudo sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
